apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  sessionAffinity: None
  # Using the 'NodePort' type to expose the application on one of the ports of the application node.
  type: NodePort